### ISSUE TITLE
HTML result has `disabled` attribute hard coded on the checkbox input

### ISSUE THREAD

**Issue by brookback** [micromark/micromark-extension-gfm-task-list-item#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-extension-gfm-task-list-item@2.0.1

### Steps to reproduce

Process:

```js
import parse from 'remark-parse';
import gfm from 'remark-gfm';
import toHTML from 'remark-html';

unified()
.use(parse)
.use(gfm)
.use(toHTML)
.process(`
- [] foo
`);
```

### Expected behavior

```html
<input type="checkbox">
```

### Actual behavior

```html
<input type="checkbox" disabled="">
```
Checkbox is disabled due to this hard coded line: https://github.com/micromark/micromark-extension-gfm-task-list-item/blob/main/dev/lib/html.js#L17

Maybe it can be configured somehow, to opt-out of the disabled default?

### Runtime

Node v16

### OS

macOS

**Comment by wooorm** [comment]
And then? You’d still need to do other things to make a form. What’s your use case?

**Comment by wooorm** [comment]
If you can add event listeners, then you can also remove attributes indeed!

You should then also add names to each checkbox. And likely wrap in a form (or associate a form otherwise). Depends on where you want to store this info.

**Comment by brookback** [comment]
Sure. But may I ask why the default state is `disabled: true`?

**Comment by ChristianMurphy** [comment]
It is set in the standard https://github.github.com/gfm/#task-list-items-extension-

The reason behind that markdown is a static document.
Input is interactive, it requires additional scripts, backend, and html context which isn't part of the markdown standard.

**Comment by brookback** [comment]
> It is set in the standard

Hm, no, it's not set. On the contrary, the spec literally has a paragraph saying that implementors are free to do whatever with the `disabled` prop:

> This spec does not define how the checkbox elements are interacted with: in practice, implementors are free to render the checkboxes as disabled or inmutable elements, or they may dynamically handle dynamic interactions (i.e. checking, unchecking) in the final rendered document.

**Comment by ChristianMurphy** [comment]
Use your listening ears @brookback 😉 
The standard offers two options.
Micromark is not a full stack platform it is a static and immutable document rendered.
So we offer the static and immutable disabled.

If you want to make it dynamic consider using one of our higher level packages like https://github.com/remarkjs/react-markdown
Which allows you to customize this.

**Comment by brookback** [comment]
I didn't want to come off as pushy, sorry if so. Just asking since I want to understand the goals and reasoning, and I felt your initial comments weren't exhaustive.

Thanks so much for your time!

**Comment by brookback** [comment]
(my use case is that we use Remark on the server and pass the rendered HTML to the client. Thus, I don't use the React package linked. I still want client interactions on that rendered HTML though. So it's sort of an in between the chairs of the "immutable document" and "dynamic React component" worlds).

**Comment by wooorm** [comment]
If you use remark, then the HTML part of this project isn't used! Instead, these props are defined in mdast-util-to-hast.

With hast, there are trees, which could be changed.

But it all kinda depends on what you're doing. Should every user be able to modify markdown? Should their interactions be stored in a database to their account or in local storage?
To do all of that you'd more than just the disabled prop. Client side JS, or transforming the tree, adding more info like names and forms.

So I don't think it's sensible to do *just* that

**Comment by ChristianMurphy** [comment]
> my use case is that we use Remark on the server and pass the rendered HTML to the client. Thus, I don't use the React package linked. 

The package linked can work server side, but lower level remark packages work too!

> So it's sort of an in between the chairs of the "immutable document" and "dynamic React component" worlds

It's also possible with the lower level packages.
`remark` focuses purely on markdown representation, but to render you're likely passing through `rehype`, which handles HMTL https://unifiedjs.com/learn/
`rehype` supports plugins, which allows defaults to be changed.


```ts
import type { Root } from 'hast';
import { visit } from 'unist-util-visit';

export function rehypeEnableCheckbox() {
  return function checkboxTransform(tree: Root) {
    visit(tree, 'element', (node) => {
      if (node.tagName === 'input' && node.properties.type === 'checkbox') {
        node.properties.disabled = false;
      }
    });
  };
}
```

runnable example https://stackblitz.com/edit/github-zqnym5?file=src%2Fmain.ts

**Comment by brookback** [comment]
@ChristianMurphy Huge thanks for the explanation! I use `remark-html` as a shortcut, but I see now how it's useful to drop down to the Rehype plugins separately :) I tried something like your transformer plugin, but gave up when setting `disabled` didn't work (due to me not using the plugin properly).

🙏🙏🙏
